### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lee3do** [panwrona/DownloadProgressBar#8]
Caused by: java.lang.NullPointerException
    at com.panwrona.downloadprogressbar.library.DownloadProgressBar.setCurrentPlayTimeByStateAndPlay(DownloadProgressBar.java:775)
    at com.panwrona.downloadprogressbar.library.DownloadProgressBar.continueAnimation(DownloadProgressBar.java:814)
    at com.panwrona.downloadprogressbar.library.DownloadProgressBar.onRestoreInstanceState(DownloadProgressBar.java:806)
    at android.view.View.dispatchRestoreInstanceState(View.java:12849)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
    at android.view.View.restoreHierarchyState(View.java:12827)
    at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1780)
    at android.app.Activity.onRestoreInstanceState(Activity.java:980)
    at android.app.Activity.performRestoreInstanceState(Activity.java:951)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1141)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2248)
    ... 11 more

**Comment by panwrona** [comment]
Okay, it seems that it happened while rotating the phone portrait <-> landscape. I will look into it.

**Comment by likhithk** [comment]
Even I am having same issue. Anyone with solutions for that ,then pls do reply.
